irisnet/cosmos-sdk

baseapp/router.go
=> Add new function for Router interface

x/gov/test_common.go
=> fix test error

types/account.go
Modify the bech32 prefix: cosmos--->iris
=> Modify the bech32 prefix: cosmos--->iris

types/account.go
Modify the bech32 prefix:	
Bech32PrefixAccAddr = "faa"
Bech32PrefixAccPub  = "fap"
Bech32PrefixValAddr = "fva"
Bech32PrefixValPub  = "fvp"
=> Modify the bech32 prefix:

store/rootmultistore.go, types/account.go
=>  Complete the commitID calculation logic modification

x/params/keeper.go, x/params/keeper_test.go, x/params/msg_status.go
=> add Paramstores

baseapp/baseapp_test.go, baseapp/router.go, cmd/gaia/app/app.go, store/rootmultistore.go, x/gov/test_common.go
=> update Router interface && fix bug in commitStores()

baseapp/router.go, cmd/gaia/cmd/gaiadebug/hack.go, docs/sdk/core/examples/app1.go, docs/sdk/core/examples/app2.go, docs/sdk/core/examples/app3.go, docs/sdk/core/examples/app4.go, examples/basecoin/app/app.go, examples/democoin/app/app.go, examples/democoin/x/cool/app_test.go, examples/democoin/x/pow/app_test.go, examples/kvstore/main.go, server/mock/app.go, store/rootmultistore.go, store/rootmultistore_test.go, x/bank/bench_test.go, x/ibc/app_test.go, x/mock/app_test.go, x/slashing/app_test.go, x/stake/app_test.go
=> Silei/cosmos sdk: Load not used stores in the new version

baseapp/baseapp.go
=> setup runMsg callback function

cmd/gaia/app/app.go, cmd/gaia/app/genesis.go, cmd/gaia/cli_test/cli_test.go, cmd/gaia/cmd/gaiacli/main.go, types/coin.go, x/bank/msgs_test.go, x/gov/client/cli/tx.go, x/gov/handler.go, x/gov/keeper.go, x/gov/msgs.go, x/gov/proposals.go, x/gov/proposals_test.go, x/gov/wire.go, x/params/client/cli/util.go, x/params/genesis.go, x/stake/types/validator.go
1:Implement the gov function parametersProposal, currently only modify the parameter type to string
2:Param store adds startup configuration parameters: the precision of a certain token, the query token accuracy method, and the conversion method
For Admin Use:
=> Implement the gov function parametersProposal

x/gov/genesis.go, x/gov/keeper.go, x/gov/proposals.go, x/gov/wire.go
=> add SoftwareUpgradeProposal

x/gov/client/rest/util.go, x/slashing/client/rest/tx.go, x/stake/client/rest/tx.go
=> Add fee in rest server

Gopkg.lock, Gopkg.toml
=> update tendermint deps to v0.22.6-iris1

client/context/helpers.go, cmd/gaia/app/app.go, cmd/gaia/app/genesis.go, cmd/gaia/cli_test/cli_test.go, types/coin.go, types/coin_test.go, types/coin_type.go, types/coin_type_test.go, types/rational.go, types/rational_test.go, x/auth/feekeeper.go, x/auth/feekeeper_test.go, x/bank/client/cli/sendtx.go, x/gov/client/cli/tx.go, x/gov/genesis.go, x/gov/keeper_test.go, x/gov/tally_test.go, x/gov/test_common.go, x/slashing/app_test.go, x/slashing/test_common.go, x/stake/app_test.go, x/stake/client/cli/tx.go, x/stake/types/params.go
=> Add coinType to support multiple units of tokens

client/context/helpers.go, cmd/gaia/app/app.go, cmd/gaia/app/genesis.go, types/coin_type.go, x/auth/feekeeper.go, x/gov/client/cli/tx.go, x/gov/client/rest/rest.go, x/gov/genesis.go, x/stake/client/cli/tx.go, x/stake/types/params.go
=> iris：add notes

types/coin_type.go
=> iris: modify coin_type

store/rootmultistore.go, store/rootmultistore_test.go
=> cherry pick the rootmultistore changes

store/multistoreproof.go, store/multistoreproof_test.go, store/rootmultistore.go, x/auth/feekeeper.go
=> Add proof in query for lcd and add fee refund

Gopkg.lock, types/errors.go
=> Silei/refactor:  add new error

x/stake/keeper/slash.go
=> fix slash amount issue

types/account.go, x/stake/keeper/slash.go
=> irisnet : modify bech32 prefix

x/stake/handler.go, x/stake/keeper/delegation.go
Fix bug: http://jira.bianjie.ai/browse/IRISHUB-227
=> IRISHUB-227: add affected voting power checking

x/stake/handler.go, x/stake/types/validator.go
Fix bug: http://jira.bianjie.ai/browse/IRISHUB-244
=> IRISHUB-244: remove precision in power calculation

cmd/gaia/app/genesis.go, x/stake/keeper/delegation.go, x/stake/keeper/delegation_test.go, x/stake/keeper/slash_test.go, x/stake/keeper/validator_test.go, x/stake/types/validator.go, x/stake/types/validator_test.go
Fix bug: http://jira.bianjie.ai/browse/IRISHUB-245
=> IRISHUB-245: change int64 to sdk.Int in AddTokensFromDel

x/stake/handler.go, x/stake/keeper/slash.go
=> merge Irisnet/hotfix v0.23.0 iris2 into master

client/context/context.go, client/context/query.go, client/flags.go, client/lcd/root.go, store/multistoreproof.go, store/multistoreproof_test.go, store/rootmultistore.go
Refactor code according to code reviewer: https://github.com/cosmos/cosmos-sdk/pull/2192
=> PR part one, refactor code according to code reviewers

Gopkg.lock, client/context/context.go
Previously the deps tools vesion was too old. Update it and rerun this command:
```
make update_vendor_deps
```
=> IRISHUB-238: fix test_lint failure

x/slashing/params.go, x/stake/types/params.go
=> Change slash window and unbond time

Gopkg.lock, Gopkg.toml, x/stake/handler.go
=> Irisnet/hotfix v0.23.0 iris2

x/stake/genesis.go
http://jira.bianjie.ai/browse/IRISHUB-393
=> IRISHUB-393: missing to set validator intraTxCount in stake genesis init

x/stake/genesis.go
=> Irisnet/hotfix v0.23.0 iris4

store/rootmultistore.go
http://jira.bianjie.ai/browse/IRISHUB-524
=> IRISHUB-524: Add check for iavl proof and value before building multistore proof

x/stake/keeper/key.go, x/stake/keeper/val_state_change.go, x/stake/types/validator.go
=> R4R:modify validator.Tokens to GetPower()

client/context/query.go, x/ibc/02-client/client/rest/query.go, x/ibc/02-client/types/keys.go, x/ibc/03-connection/client/rest/query.go, x/ibc/03-connection/types/keys.go, x/ibc/04-channel/client/rest/query.go, x/ibc/04-channel/types/keys.go
=> return query result proof
